server:
  port: 0

spring:
  cloud:
    gateway:
      rsocket:
        client:
          service-name: refreshing-client
          tags:
            INSTANCE_NAME: ${'refreshing-client' + random.int}
            multicast: true
          forwarding:
            refreshing-service-rr: 
              service_name: refreshing-service
          broker:
            host: localhost
            port: 7003
